# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81037c4c937feff2bdfb09edf0cf35bf07b8ef4e4142973c9578c7b66d417509aa158053ca1abb98bc366a8b9df2c127ff0b11032448dd82e4b8ce86d87c7f57

test:
  secret_key_base: 8df369d10f80c6bc9df40114bc3106d83d4467ab317d12f8bb71af4df494d129543eae4fe0b18f76c644b1d5c1529ba026c1c9897ad32bb45431ad61506990ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
